### ISSUE TITLE
Playground stuck on the splashscreen with latest Uno dev version

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/Uno.Playground#101]
## Current behavior

Playground stuck on the splashscreen with latest Uno dev version

## Expected behavior

Playground should load correctly

## How to reproduce it (as minimally and precisely as possible)

Use the latest canary version of the playground: https://playgroundcanary.z19.web.core.windows.net/

## Environment

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X] WebAssembly (Playground)
- [ ] Windows
- [ ] Build tasks

Browser tested:
- Chrome (version 79.0.3945.130)
- Chromium (version 79.0.3945.130)
- Firefox version : (72.0.2)

**Comment by jeromelaban** [comment]
Fixed (mono.wasm is now dotnet.wasm /cc @benventive)
